### ISSUE TITLE
The results of PSEnet on ctw1500?

### ISSUE THREAD

**Issue by seekingdeep** [PaddleEdu/OCR-models-PaddlePaddle#2]
Hi there,
- How does your implementation of PSENet perform on the ctw1500 dataset?

**Comment by xmy0916** [comment]
@seekingdeep sorry, we didn't test it on ctw1500.

**Comment by seekingdeep** [comment]
ctw1500 includes long and short textlines, that can resemble the document images that the users would try to predict on.
